### ISSUE TITLE
Split factories into separate files

### ISSUE THREAD

**Issue by azranel** [NetguruCodeCollege/team_alpha_project#54]
https://github.com/NetguruCodeCollege/team_alpha_project/blob/c7b83a1b972dfefa43ef4f02c99b44d90151ef4d/spec/factories.rb#L1-L16

Place those files in `spec/factories/` directory. Each of those files should be named by model for which factories are (ex. `User` model will have factories defined in `spec/factories/user.rb`)

**Comment by mar-kow** [comment]
Thanks for this tip! I changed it.
