### ISSUE TITLE
Make matchers consistent

### ISSUE THREAD

**Issue by azranel** [NetguruCodeCollege/team_alpha_project#55]
https://github.com/NetguruCodeCollege/team_alpha_project/blob/c7b83a1b972dfefa43ef4f02c99b44d90151ef4d/spec/models/user_spec.rb#L3-L20

In some places you use `is_expected.to` and in other you use `should`. It's always better to be consistent. Please change them to newer syntax which is `is_expected.to`

**Comment by mar-kow** [comment]
Thanks for your advice. I have changed it. 

https://github.com/NetguruCodeCollege/team_alpha_project/pull/62
